# Generated by Django 5.0.7 on 2024-09-12 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0007_profilecounter_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveApproval',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('approvedBy', models.CharField(max_length=40)),
                ('role', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='leavePolicies',
            fields=[
                ('leaveType', models.CharField(choices=[('earnedLeave', 'EL'), ('sickLeave', 'SL'), ('maternityLeave', 'ML'), ('casualLeave', 'CL')], max_length=40, primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField()),
                ('CarryOverLimit', models.CharField(max_length=6)),
                ('payoutPolicy', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='leaveRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('duration', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('allowed', 'allowed'), ('rejected', 'rejected'), ('pending', 'pending')], max_length=50)),
                ('description', models.TextField()),
                ('time', models.TimeField()),
                ('empId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profilecounter')),
                ('leaveType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaveManagement.leavepolicies')),
            ],
        ),
    ]
