# Generated by Django 5.0.7 on 2024-09-12 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveManagement', '0002_alter_leavepolicies_leavetype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavepolicies',
            name='leaveType',
            field=models.CharField(choices=[('casualLeave', 'CL'), ('earnedLeave', 'EL'), ('sickLeave', 'SL'), ('maternityLeave', 'ML')], max_length=40, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('rejected', 'rejected'), ('allowed', 'allowed')], max_length=50),
        ),
    ]
