# Generated by Django 5.0.7 on 2024-09-12 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveManagement', '0005_alter_leavepolicies_leavetype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavepolicies',
            name='leaveType',
            field=models.CharField(choices=[('sickLeave', 'SL'), ('maternityLeave', 'ML'), ('earnedLeave', 'EL'), ('casualLeave', 'CL')], max_length=40, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('allowed', 'allowed'), ('pending', 'pending'), ('rejected', 'rejected')], max_length=50),
        ),
    ]
