# Generated by Django 5.0.7 on 2024-09-12 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveManagement', '0006_alter_leavepolicies_leavetype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('rejected', 'rejected'), ('allowed', 'allowed'), ('pending', 'pending')], max_length=50),
        ),
    ]
