# Generated by Django 5.0.7 on 2024-09-12 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaveManagement', '0007_alter_leaverequest_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeaveApproval',
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='approvalTime',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='approvaldate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='approvedBy',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='leavepolicies',
            name='leaveType',
            field=models.CharField(choices=[('sickLeave', 'SL'), ('earnedLeave', 'EL'), ('maternityLeave', 'ML'), ('casualLeave', 'CL')], max_length=40, primary_key=True, serialize=False, unique=True),
        ),
    ]
