# Generated by Django 5.1 on 2024-08-29 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='JobOpenings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('Totalvacancies', models.IntegerField()),
                ('requiredSkills', models.CharField(max_length=60)),
                ('filledvacancies', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='leave',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('leaveType', models.CharField(choices=[('PL', 'PRIVILEDGED_LEAVE'), ('SL', 'SICK_LEAVE'), ('CL', 'CASUAL_LEAVE'), ('ML', 'MATERNITY_LEAVE')], max_length=30)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee_Leave',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('StartDate', models.DateField()),
                ('endDate', models.DateField()),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('pending', 'Pending')], max_length=40)),
                ('empId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
                ('Lid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.leave')),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('contact', models.CharField(max_length=15)),
                ('designation', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=80)),
                ('doj', models.DateField()),
                ('salary', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('requiredSkills', models.TextField()),
                ('dId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.department')),
            ],
        ),
        migrations.CreateModel(
            name='employee_project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=40)),
                ('hoursWorked', models.CharField(max_length=30)),
                ('empId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
                ('pId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.project')),
            ],
        ),
        migrations.CreateModel(
            name='salary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('basic_salary', models.CharField(max_length=50)),
                ('allowance', models.CharField(max_length=50)),
                ('deductions', models.CharField(max_length=50)),
                ('net_sal', models.CharField(max_length=50)),
                ('empId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
