# Generated by Django 5.0.7 on 2024-09-12 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_profilecounter_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='empid',
            field=models.IntegerField(default=1000, unique=True),
        ),
    ]
