# Generated by Django 5.0.7 on 2024-09-12 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_profilecounter_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilecounter',
            name='id',
        ),
        migrations.AlterField(
            model_name='profilecounter',
            name='EmpId',
            field=models.IntegerField(default=1000, primary_key=True, serialize=False, unique=True),
        ),
    ]
