# Generated by Django 5.0.7 on 2024-09-12 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_remove_profilecounter_id_alter_profilecounter_empid'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='empCode',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
